spring.application.name=vaccine-system

# 最大审批次数（超过此次数的用户不出现在待审批列表中）
registration.maxDingApprovalCount=3
registration.maxMeetingApprovalCount=3
server.port=8080

# Thymeleaf 配置（不缓存，方便开发）
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html



# MyBatis-Plus
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml
mybatis-plus.global-config.db-config.logic-delete-field=isDeleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

