spring.application.name=vaccine-system
server.port=8080

# Thymeleaf 配置（不缓存，方便开发）
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html



# MyBatis-Plus
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml
mybatis-plus.global-config.db-config.logic-delete-field=isDeleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# JWT
jwt.secret=vaccine-system-secret-key-2025-very-long-string
jwt.expiration=604800000

# WeChat Mini Program
wx.dev-mode=true
wx.appid=wx3e96ea006cbdfd58
wx.secret=31d54ce1e755d7aa6f3ae7525cf2cb15

# Admin
admin.username=admin
admin.password=admin123
